version: '3.5'

services:
  api:
    container_name: kinobu_api_dev
    env_file: .env
    build:
      context: .
      dockerfile: ./build/dev.dockerfile
    command: npm run start:debug
    ports:
      - 3010:3010
      - 9229:9229
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres: