export const HEALTH_CHECKER_SERVICE = Symbol('HEALTH_CHECKER_SERVICE');
export const TYPEORM_HEALTH_INDICATOR = Symbol('TYPEORM_HEALTH_INDICATOR');
export const HEALTH_CHECKER_INDICATOR = Symbol('HEALTH_CHECKER_INDICATOR');
